/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LinksRouteImport } from './routes/links'
import { Route as JarvisRouteImport } from './routes/jarvis'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as HorizonRouteImport } from './routes/horizon'
import { Route as DesktopRouteImport } from './routes/desktop'
import { Route as ContextRouteImport } from './routes/context'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const JarvisRoute = JarvisRouteImport.update({
  id: '/jarvis',
  path: '/jarvis',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const HorizonRoute = HorizonRouteImport.update({
  id: '/horizon',
  path: '/horizon',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopRoute = DesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/context': typeof ContextRoute
  '/desktop': typeof DesktopRoute
  '/horizon': typeof HorizonRoute
  '/images': typeof ImagesRoute
  '/insights': typeof InsightsRoute
  '/jarvis': typeof JarvisRoute
  '/links': typeof LinksRoute
  '/messages': typeof MessagesRoute
  '/prompts': typeof PromptsRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/context': typeof ContextRoute
  '/desktop': typeof DesktopRoute
  '/horizon': typeof HorizonRoute
  '/images': typeof ImagesRoute
  '/insights': typeof InsightsRoute
  '/jarvis': typeof JarvisRoute
  '/links': typeof LinksRoute
  '/messages': typeof MessagesRoute
  '/prompts': typeof PromptsRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/context': typeof ContextRoute
  '/desktop': typeof DesktopRoute
  '/horizon': typeof HorizonRoute
  '/images': typeof ImagesRoute
  '/insights': typeof InsightsRoute
  '/jarvis': typeof JarvisRoute
  '/links': typeof LinksRoute
  '/messages': typeof MessagesRoute
  '/prompts': typeof PromptsRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/context'
    | '/desktop'
    | '/horizon'
    | '/images'
    | '/insights'
    | '/jarvis'
    | '/links'
    | '/messages'
    | '/prompts'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/context'
    | '/desktop'
    | '/horizon'
    | '/images'
    | '/insights'
    | '/jarvis'
    | '/links'
    | '/messages'
    | '/prompts'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/context'
    | '/desktop'
    | '/horizon'
    | '/images'
    | '/insights'
    | '/jarvis'
    | '/links'
    | '/messages'
    | '/prompts'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  ContextRoute: typeof ContextRoute
  DesktopRoute: typeof DesktopRoute
  HorizonRoute: typeof HorizonRoute
  ImagesRoute: typeof ImagesRoute
  InsightsRoute: typeof InsightsRoute
  JarvisRoute: typeof JarvisRoute
  LinksRoute: typeof LinksRoute
  MessagesRoute: typeof MessagesRoute
  PromptsRoute: typeof PromptsRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jarvis': {
      id: '/jarvis'
      path: '/jarvis'
      fullPath: '/jarvis'
      preLoaderRoute: typeof JarvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horizon': {
      id: '/horizon'
      path: '/horizon'
      fullPath: '/horizon'
      preLoaderRoute: typeof HorizonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop': {
      id: '/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  ContextRoute: ContextRoute,
  DesktopRoute: DesktopRoute,
  HorizonRoute: HorizonRoute,
  ImagesRoute: ImagesRoute,
  InsightsRoute: InsightsRoute,
  JarvisRoute: JarvisRoute,
  LinksRoute: LinksRoute,
  MessagesRoute: MessagesRoute,
  PromptsRoute: PromptsRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
